config/routes.rb
Rails.application.routes.draw do
  resources :collections

  resources :links

  resources :images

  devise_for :users
  root to: 'pages#root'
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user
  has_many :images, dependent: :destroy
  has_many :links, dependent: :destroy

  validates :user_id, :name, presence: true

  scope :shared, -> { where(share: true) }

  def self.for_select(user)
    where(user_id: user.id).order(name: :asc).pluck(:name, :id)
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :collection
  mount_uploader :image, ImageUploader

  validates :name, :image, :collection_id, presence: true
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :collection

  validates :link, :collection_id, presence: true
  validates :link, url: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def redirect_message(object = nil)
    flash.now[:alert] = object.errors.full_messages.join(', ') if object.try(:errors)
  end

  def notice_on(method = nil)
    return nil if method.nil?
    t "flash.notice.on_#{method}"
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def index
    load_collections
  end

  def show
    load_collection
  end

  def new
    build_collection
  end

  def create
    build_collection
    save_collection(notice_on(:create)) || render(:new)
  end

  def destroy
    load_collection
    @collection.destroy
    flash[:notice] = notice_on(:destroy)
    redirect_to redirection_path
  end

  private

  def load_collections
    @collections ||= collection_scope.where(user_id: current_user.id)
  end

  def load_collection
    @collection ||= collection_scope.find(params[:id])
  end

  def build_collection
    @collection ||= collection_scope.build
    @collection.attributes = collection_params
  end

  def save_collection(notice = nil)
    return redirect_to redirection_path, notice: notice if @collection.save
    redirect_message(@collection)
    render :new
  end

  def redirection_path
    collections_path
  end

  def collection_params
    collection_params = params[:collection]
    collection_params ? collection_params.permit(:name, :share).merge(user_id: current_user.id) : {}
  end

  def collection_scope
    Collection.all
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def show
    load_image
  end

  def new
    build_image
  end

  def create
    build_image
    save_image(notice_on(:create)) || render(:new)
  end

  def destroy
    load_image
    @image.destroy
    flash[:notice] = notice_on(:destroy)
    redirect_to redirection_path
  end

  private

  def load_images
    @images ||= image_scope
  end

  def load_image
    @image ||= image_scope.find(params[:id])
  end

  def build_image
    @image ||= image_scope.build
    @image.attributes = image_params
  end

  def save_image(notice = nil)
    return redirect_to redirection_path, notice: notice if @image.save
    redirect_message(@image)
    render :new
  end

  def redirection_path
    @image.collection
  end

  def image_params
    image_params = params[:image]
    image_params ? image_params.permit(:name, :image, :collection_id) : {}
  end

  def image_scope
    Image.all
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def show
    load_link
  end

  def new
    build_link
  end

  def create
    build_link
    save_link(notice_on(:create)) || render(:new)
  end

  def destroy
    load_link
    @link.destroy
    flash[:notice] = notice_on(:destroy)
    redirect_to redirection_path
  end

  private

  def load_links
    @links ||= link_scope
  end

  def load_link
    @link ||= link_scope.find(params[:id])
  end

  def build_link
    @link ||= link_scope.build
    @link.attributes = link_params
  end

  def save_link(notice = nil)
    return redirect_to redirection_path, notice: notice if @link.save
    redirect_message(@link)
    render :new
  end

  def redirection_path
    @link.collection
  end

  def link_params
    link_params = params[:link]
    link_params ? link_params.permit(:name, :link, :collection_id) : {}
  end

  def link_scope
    Link.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def root
    load_collections
  end

  private

  def load_collections
    @collections ||= collection_scope.shared
  end

  def collection_scope
    Collection.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_notice(except: [])
    flash.select { |name, _msg| except.exclude?(name.to_sym) }.map do |name, msg|
      content_tag :div, msg, class: ['alert', flash_class(name)]
    end.join.html_safe
  end

  def flash_class(name)
    case name
      when 'alert'
        'alert-danger'
      when 'notice'
        'alert-success'
    end
  end
end

app/views/application/_navigation.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      = link_to 'MediaCollection', :root, class: 'navbar-brand'
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if user_signed_in?
          %li.active
            = link_to t('collections.plural'), collections_path
      = render 'user_navigation'

app/views/application/_user_navigation.html.haml
%ul.nav.navbar-nav.navbar-right
  - if user_signed_in?
    %li= link_to t('sign_out'), destroy_user_session_path, method: 'delete'
  - else
    %li= link_to t('sign_in'), new_user_session_path
    %li= link_to t('sign_up'), new_user_registration_path

app/views/collections/_form.html.haml
= form_for @collection, builder: MainFormBuilder do |f|

  = f.text_field_bootstrap :name
  = f.check_box_bootstrap :share

  = f.main_submit

app/views/collections/index.html.haml
%h1= t('collections.plural')

%table.table.table-striped
  %tr
    %th= Collection.human_attribute_name('name')
    %th= Collection.human_attribute_name('share')
    %th
    %th

  - @collections.each do |collection|
    %tr
      %td= collection.name
      %td= collection.share
      %td= link_to t('show'), collection
      %td= link_to t('destroy'), collection, method: :delete, data: { confirm: t('confirmations.are_you_sure') }

%br

= link_to t('button_add', object_name: t('collections.accusative')), new_collection_path, class: 'btn btn-success'
= link_to t('button_add', object_name: t('images.accusative')), new_image_path, class: 'btn btn-success'
= link_to t('button_add', object_name: t('links.accusative')), new_link_path, class: 'btn btn-success'

app/views/collections/new.html.haml
%h1= t('title.new', object_name: t('activerecord.models.collection'))

= render 'form'

= link_to t('back'), collections_path

app/views/collections/show.html.haml
- @collection.images.each do |image|
  = image_tag image.image.thumb, class: 'img-thumbnail'
  %br

- @collection.links.each do |link|
  = link_to link.name, link.link
  %br

= link_to t('back'), collections_path

app/views/images/_form.html.haml
= form_for @image, builder: MainFormBuilder do |f|

  = f.text_field_bootstrap :name
  = f.image_field_bootstrap :image
  = f.select_field_bootstrap :collection_id, Collection.for_select(current_user), {}

  = f.main_submit

app/views/images/new.html.haml
%h1= t('title.new', object_name: t('activerecord.models.image'))

= render 'form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MediaCollection
    %meta{ charset: 'utf-8' }
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      .row
        = render 'application/navigation'
        .col-lg-12
          = flash_notice
        = yield

app/views/links/_form.html.haml
= form_for @link, builder: MainFormBuilder do |f|
  = f.text_field_bootstrap :name
  = f.text_field_bootstrap :link
  = f.select_field_bootstrap :collection_id, Collection.for_select(current_user), {}

  = f.main_submit

app/views/links/new.html.haml
%h1= t('title.new', object_name: t('activerecord.models.link'))

= render 'form'

app/views/pages/root.html.haml
- if @collections.present?
  %h2= t('available_collection')
  - @collections.each do |collection|
    = link_to collection.name, collection
    %br
- else
  %h2= t('not_have_collection')